### ISSUE TITLE
script to check and automatically fix DNS problems

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/data-life-cycle-cloud-docker-jupyterhub#22]
To prevent #21 from happening every so often, we should run some checker for the DNS problems and fix if necessary.   Could run continuously or in cron, I guess.

**Comment by isuftin** [comment]
I've implemented a task in RunDeck that will run once per week, on Sunday, to maintain DNS pointing to the load balancer that JupyterHub sits behind.

**Comment by rsignell-usgs** [comment]
Does this mean that in the future, we could be down for up to a week?
Or is this sufficient to prevent future issues?
