### ISSUE TITLE
Creating custom conda environments

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/data-life-cycle-cloud-docker-jupyterhub#5]
I want to use a custom conda environment (IOOS), so I logged into JupyterHub, opened a new terminal, and did:
```
cd work
wget https://raw.githubusercontent.com/ioos/notebooks_demos/master/environment.yml
conda env create -f environment.yml
```
and after about 20 minutes of package downloading, it appears to have completed successfully:
```
[I 15:02:41 InstallContribNbextensionsApp] - Validating: OK
[I 15:02:41 InstallContribNbextensionsApp] Installing jupyter_contrib_nbextensions items to config in /opt/conda/envs/
IOOS3/etc/jupyter
Enabling: jupyter_nbextensions_configurator
- Writing config: /opt/conda/envs/IOOS3/etc/jupyter
    - Validating...
      jupyter_nbextensions_configurator  OK
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Enabling tree nbextension nbextensions_configurator/tree_tab/main...
[I 15:02:41 InstallContribNbextensionsApp] Enabling notebook extension contrib_nbextensions_help_item/main...
[I 15:02:41 InstallContribNbextensionsApp]       - Validating: OK
[I 15:02:41 InstallContribNbextensionsApp] - Editing config: /opt/conda/envs/IOOS3/etc/jupyter/jupyter_nbconvert_confi
g.json
[I 15:02:41 InstallContribNbextensionsApp] --  Configuring nbconvert template path
[I 15:02:41 InstallContribNbextensionsApp] --  Configuring nbconvert preprocessors
[I 15:02:41 InstallContribNbextensionsApp] - Writing config: /opt/conda/envs/IOOS3/etc/jupyter/jupyter_nbconvert_confi
g.json
[I 15:02:41 InstallContribNbextensionsApp] --  Writing updated config file /opt/conda/envs/IOOS3/etc/jupyter/jupyter_n
bconvert_config.json

#
# To activate this environment, use:
# > source activate IOOS3
#
# To deactivate an active environment, use:
# > source deactivate
#

jovyan@b17837619c90:~/work$
```

**Comment by rsignell-usgs** [comment]
The problem, however, is that the environments are not being advertised in Jupyter.   I'm wondering whether the base conda environment that kicked off the Juptyterhub server perhaps did not have the `nb_conda_kernels` package installed?

**Comment by rsignell-usgs** [comment]
Ah, wait, I can check this:
```
source deactivate IOOS3
conda info -e
conda list nb_conda_kernels
```
indeed shows nothing

**Comment by rsignell-usgs** [comment]
So I did:
```
conda install nb_conda_kernels
```
and did "stop my server" and then "start my server" from the dashboard, and now I get:
```
500 : Internal Server Error
Spawner failed to start [status=1]
```

**Comment by rsignell-usgs** [comment]
I tried reloading 
https://jupyterhub.wma.usgs.chs.ead/user/rsignell-usgs
and now I'm getting: 
```
This page isn’t working

jupyterhub.wma.usgs.chs.ead redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```
I did try clearing cookies, but it didn't help.

**Comment by isuftin** [comment]
I think the issue ended up being: https://stackoverflow.com/questions/39604271/conda-environments-not-showing-up-in-jupyter-notebook

So I did the following:

```
conda install jupyter
cd work
wget https://raw.githubusercontent.com/ioos/notebooks_demos/master/environment.yml
conda env create -f environment.yml
source activate IOOS3
conda list nb_conda_kernels
# packages in environment at /opt/conda/envs/IOOS3:
#
nb_conda_kernels          2.1.0                    py36_0    conda-forge
```

**Comment by isuftin** [comment]
@rsignell-usgs So is your suggestion to build the IOOS kernel as part of the notebook image that we are deploying as a Docker container? If so, should the above be enough or is there other instructions to follow to get that installed for Jupyter Notebook?

**Comment by isuftin** [comment]
Also looking @ http://ioos.github.io/notebooks_demos/other_resources/

@rsignell-usgs Should I just follow that for the base notebook env?

**Comment by rsignell-usgs** [comment]
I do think it makes sense to do so.  That way folks will have a met/ocean modeling obs environment ready to go.  Like the full Anaconda distribution, where they try to give folks a bit env to suite most people's needs.   But here was are tuning it for our community.  :smile_cat:

**Comment by rsignell-usgs** [comment]
So I tried restarting my Jupyterhub server, and seems like my environment stuff did not get persisted:
```
W
jovyan@c5ccf33fe758:~$ conda info -e
# conda environments:
#
root                  *  /opt/conda
```
I tried doing `import iris` in the root environment, but did not work, so I guess the root env is not the IOOS env yet. 

I did notice that the  `environment.yml` is still there, so I'm trying to create the env again:
```
conda create env -f environment.yml
```
okay, and there is my environment:
```

jovyan@c5ccf33fe758:~/work$ conda info -e
# conda environments:
#
IOOS3                    /opt/conda/envs/IOOS3
root                  *  /opt/conda
```
but when I visit jupyter, it's not selectable as a kernel.  I only see `Python 3`.

**Comment by rsignell-usgs** [comment]
I tried shutting down and starting up, and now I'm getting:
```
500 : Internal Server Error
The error was:
Permission failure checking authorization, I may need a new token
```

**Comment by isuftin** [comment]
@rsignell-usgs I think the base image needs to be built with the IOOS3 env in order for that to be an option for users. I plan on doing that today.

As far as shutting down/starting up, I think that's a bug in the type of spawner I'm using to control the swarm. Typically users will not have the ability to do that as I *think* that's an admin only function. I need to work through that issue with the author of the SwarmSpawner JupyterHub spawner ( https://github.com/cassinyio/SwarmSpawner ). So for now, I wouldn't shut down/restart your server. I will make a new issue for that.

**Comment by rsignell-usgs** [comment]
@isuftin, we need users to be able to create their own environments and then select them from Jupyter.    If  it's possible with regular Jupyter (mine works this way), it should be possible with Jupyterhub, no?

**Comment by isuftin** [comment]
@rsignell-usgs I would think that's possible, yes. How do you do so with regular Jupyter?

**Comment by rsignell-usgs** [comment]
https://github.com/Anaconda-Platform/nb_conda_kernels

**Comment by isuftin** [comment]
Ah ok. So you're referring to being able to choose different kernels (environments). Understood. That's what I'm working on now for pre-installing the IOOS environment. 

I'm not sure if JupyterHub lets users install and then choose their environment from that dropdown.

**Comment by isuftin** [comment]
I will deploy the updated Dockerfile merged here: https://github.com/USGS-CMG/data-life-cycle-cloud-docker-jupyterhub/commit/564d89026ca1bb6b1b37437992222c500b817a26

Tested locally and the environments show up when logging into JupyterHub

**Comment by isuftin** [comment]
@rsignell-usgs This is now ready to test. 

This is what I am seeing:

![image](https://user-images.githubusercontent.com/928288/29627110-9cf436bc-87f6-11e7-86eb-fec8bad0b47d.png)

![image](https://user-images.githubusercontent.com/928288/29627230-054e26fa-87f7-11e7-9a28-1e55d787018a.png)

**Comment by rsignell-usgs** [comment]
I just tried logging in and creating a custom environment by starting my server, opening a new terminal, and typing:
```
conda create -n obspy python=3 obspy
```
The conda create process worked fine until the end, where it reported:
```
pyqt-4.11.4-py 100% |######################################################################| Time: 0:00:00   5.72 MB/s
requests-2.18. 100% |######################################################################| Time: 0:00:00  23.54 MB/s
matplotlib-1.5 100% |######################################################################| Time: 0:00:00   9.03 MB/s
obspy-1.0.3-py 100% |######################################################################| Time: 0:00:02   8.47 MB/s

CondaError: AssertionError('/opt/conda/pkgs/ca-certificates-2017.7.27.1-0',)
CondaError: AssertionError('/opt/conda/pkgs/ca-certificates-2017.7.27.1-0',)
CondaError: AssertionError('/opt/conda/pkgs/ca-certificates-2017.7.27.1-0',)
```

**Comment by isuftin** [comment]
@rsignell-usgs I am assuming this is the issue: https://github.com/conda/conda/issues/5712

I will take a look to see how we should fix this tomorrow.

**Comment by isuftin** [comment]
The problem here is that if I implement the fix mentioned in the linked issue (not using conda clean), the Docker image size balloons back. Unfortunate but it seems this is an issue with Conda + Docker.

**Comment by rsignell-usgs** [comment]
Why do we care about the docker image size?

**Comment by isuftin** [comment]
@rsignell-usgs Ideally we'd like to keep the images lean so clustered nodes can download them, decompress them and deploy them quickly. It's a best practice when creating Dockerfiles. Looks like that's getting in the way of us being able to run properly here.

**Comment by rsignell-usgs** [comment]
Just so I have a better feeling of what we are talking about here:  how long does it take to download, decompress and deploy a 3GB and a 9GB image? 

Is it like 3secs vs 9 secs, or 30 secs vs 90 secs?

**Comment by isuftin** [comment]
@rsignell-usgs It's a binary transfer from within our data center to AWS, which I've seen take 14+ minutes, depending on how congested the network at the data center is. However, I should mention that this is a one-time transfer to any node that will be hosting the notebook containers. Typically this will be a single node to start with. Once the container image is transferred to the node, subsequent notebook launches take seconds. 

The transfer takes the bulk of the time. Decompression can take a minute or so and then actual launching takes about 3 or 4 seconds.

**Comment by rsignell-usgs** [comment]
Thanks for the great explanation.

**Comment by isuftin** [comment]
@rsignell-usgs I've figured out the problem. When the Docker container is built, the Dockerfile switches the active user to root to perform the conda installations. This causes an issue because then /opt/conda has all subdirs owned by root. The problem arises when the notebook user (jovyan) attempts conda installations. The error you saw was a permissions error in manipulating installed conda packages.

I've reconfigured the Docker image and am installing all conda stuff as jovyan. This allows the notebook user to then perform any conda related installations as normal without permissions errors. I've tested this by performing your installation steps outlined above and it works fine. 

![image](https://user-images.githubusercontent.com/928288/29673945-59ac33d0-88b6-11e7-93cc-96ae1261935e.png)

A new Docker image will be built for the single-user notebook and you can test that out once it's up and running. I'll ping you when that's ready for testing.

**Comment by rsignell-usgs** [comment]
@julienchastang, you have covered this ground before.     Can you please verify that we are on the right path here?

**Comment by isuftin** [comment]
@rsignell-usgs Ready to test

**Comment by rsignell-usgs** [comment]
Okay, I logged in, started my server, opened a terminal, and typed:
```
conda create -n test python=3 nb_conda_kernels
```
This created an environment without problem (no certificate issue):
```
# conda environments:
#
IOOS3                    /opt/conda/envs/IOOS3
ipykernel_py3            /opt/conda/envs/ipykernel_py3
test                     /opt/conda/envs/test
root                  *  /opt/conda
```

And SUCCESS!!  I can see this newly created environment in the drop down menu on my server!

I'm a bit concerned that this environment is getting created in /opt/conda/envs, however.    Each user should have their own space and environments, no?

On the Unidata JupyterHub instance, when I open a terminal, I'm in 
```
/notebooks/rsignell
```
and when I check my environments, I get this:
```
rsignell@31dda5a1bd4a:/notebooks/rsignell$ conda info -e
# conda environments:
#
test                     /home/rsignell/.conda/envs/test
globus                   /opt/conda/envs/globus
root                  *  /opt/conda
```

**Comment by rsignell-usgs** [comment]
The good news, is, however, that new environments I create via a terminal on CHS JupyterHub are now instantly available for selection in the Server!

**Comment by isuftin** [comment]
@rsignell-usgs Do remember that each user gets their own Docker container as a notebook server. So your `/opt/conda/envs` will be in your own Docker Container and volume. Another user will have their own `/opt/conda/envs`.

**Comment by isuftin** [comment]
@rsignell-usgs Of course, the drawback here is there isn't sharing between users of anything. Everything is encapsulated completely between each user. Let me know if users sharing filespace is something you wanted.

**Comment by rsignell-usgs** [comment]
@isuftin , yes, we want a modeler to be able to upload a large amount of model output and have others be able to read the data.

**Comment by isuftin** [comment]
@rsignell-usgs There are a few options we can use here. When you refer to a large amount of model output, how large are we talking and how large of a filesystem do you envision needing over time?

**Comment by rsignell-usgs** [comment]
Let's discuss this on #14.    I think we can close the custom environment issue now, following my successful tests!

**Comment by rsignell-usgs** [comment]
Just a reminder here that to be persisted, custom conda environments need to be under the `/home` volume mount. 

So my `~/.condarc` looks like this:

```
$more ~/.condarc
```
```
channels:
  - conda-forge
  - defaults
envs_dirs:
  - /home/jovyan/work/envs
```
